import { describe, expect, it } from "vitest";
import { InMemoryGitHubReconciliationRepository } from "../../../development-control-store/src";
import {
  DAB2B2_EXPECTED_SHA, DAB2B2_MATTHEW_ACTOR_ID, DAB2B2_REPOSITORY_ID, DAB2B2_SPECIFICATION_HASH,
  FixtureGitHubClient, approvalFixture, calculateBackoff, createReadOnlyGitHubClient, diagnoseReconciliationLag, evaluateApprovalEvidence, fixturePage,
  mutableIssueFixture, normalizeGitHubObservation, normalizeGitHubObservations, reconcileGitHub, refFixture,
  type GitHubApprovalExpectation, type GitHubIdentityPolicy, type GitHubReadPage,
} from "..";

const policy: GitHubIdentityPolicy = { repositoryId: DAB2B2_REPOSITORY_ID, approvingActorId: DAB2B2_MATTHEW_ACTOR_ID };
const expectation: GitHubApprovalExpectation = { repositoryId: DAB2B2_REPOSITORY_ID, taskId: "DAB-2B2", specificationRevision: 1, specificationHash: DAB2B2_SPECIFICATION_HASH, expectedOriginMainSha: DAB2B2_EXPECTED_SHA, categories: ["scope", "editing"] };
const clock = { now: () => "2026-07-13T22:00:00.000Z" };

async function run(observations = [approvalFixture()]) {
  const store = new InMemoryGitHubReconciliationRepository();
  const result = await reconcileGitHub({ repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client: new FixtureGitHubClient([fixturePage(observations)]), store, clock, identityPolicy: policy, approvalExpectation: expectation });
  return { store, result };
}

describe("DAB-2B2 read-only GitHub reconciliation", () => {
  it("normalizes stable bounded evidence without retaining source content", () => { const evidence = normalizeGitHubObservation(approvalFixture()); expect(evidence.evidenceId).toMatch(/^github_evidence_[0-9a-f]{64}$/); expect(evidence).not.toHaveProperty("content"); expect(evidence.approvalBinding).toEqual({ taskId: "DAB-2B2", specificationRevision: 1, specificationHash: DAB2B2_SPECIFICATION_HASH, expectedOriginMainSha: DAB2B2_EXPECTED_SHA, categories: ["editing", "scope"] }); });
  it("is input-order independent", () => { const inputs = [approvalFixture(), refFixture()]; expect(normalizeGitHubObservations(inputs)).toEqual(normalizeGitHubObservations([...inputs].reverse())); });
  it("deduplicates exact observations", () => expect(normalizeGitHubObservations([approvalFixture(), approvalFixture()])).toHaveLength(1));
  it("preserves conflicting same-version observations with bounded diagnostics", async () => { const first = approvalFixture(); const second = approvalFixture({ content: `${first.content}\nconflicting bounded revision` }); const { result, store } = await run([second, first]); expect(result.diagnostics.filter((item) => item.code === "conflicting_evidence")).toHaveLength(2); expect(store.listEvidence()).toHaveLength(2); });
  it("orders out-of-order versions by authoritative update time", () => { const later = approvalFixture({ updatedAt: "2026-07-13T21:39:00.000Z", content: `${approvalFixture().content}\nlater` }); const ordered = normalizeGitHubObservations([later, approvalFixture()]); expect(ordered.map((item) => item.updatedAt)).toEqual(["2026-07-13T21:38:34.000Z", "2026-07-13T21:39:00.000Z"]); });
  it("creates a new immutable evidence version for an edited comment", () => { const original = normalizeGitHubObservation(approvalFixture()); const edited = normalizeGitHubObservation(approvalFixture({ updatedAt: "2026-07-13T21:39:00.000Z", content: `${approvalFixture().content}\nBounded correction` })); expect(edited.evidenceId).not.toBe(original.evidenceId); });
  it("preserves deletion as evidence but never approval", () => { const evidence = normalizeGitHubObservation(approvalFixture({ deleted: true, content: null, updatedAt: "2026-07-13T21:40:00.000Z" })); expect(evaluateApprovalEvidence(evidence, policy, expectation).code).toBe("not_found"); });
  it("attributes a renamed login by stable numeric actor", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ actorLogin: "matthew-renamed" })), policy, expectation).code).toBe("matched"));
  it("rejects an impersonating numeric actor", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ actorId: "999" })), policy, expectation).code).toBe("not_attributable"));
  it("rejects mutable issue fields as approval", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(mutableIssueFixture()), policy, expectation).code).toBe("mutable_field_rejected"));
  it("requires the exact specification revision", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ content: approvalFixture().content!.replace("revision: 1", "revision: 2") })), policy, expectation).code).toBe("revision_mismatch"));
  it("requires the exact specification hash", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ content: approvalFixture().content!.replace(DAB2B2_SPECIFICATION_HASH, `spec_${"0".repeat(64)}`) })), policy, expectation).code).toBe("specification_hash_mismatch"));
  it("requires the exact expected SHA", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ content: approvalFixture().content!.replace(DAB2B2_EXPECTED_SHA, "0".repeat(40)) })), policy, expectation).code).toBe("stale_sha"));
  it("requires each independent category", () => expect(evaluateApprovalEvidence(normalizeGitHubObservation(approvalFixture({ content: approvalFixture().content!.replace("- Editing\n", "") })), policy, expectation).code).toBe("not_found"));
  it("rejects customer identity", () => expect(() => normalizeGitHubObservation({ ...approvalFixture(), clientId: "forbidden" } as never)).toThrowError(expect.objectContaining({ code: "CUSTOMER_IDENTITY_FORBIDDEN" })));
  it("accepts only GitHub HTTPS source URLs", () => expect(() => normalizeGitHubObservation(approvalFixture({ sourceUrl: "https://example.com/issues/18" }))).toThrowError(expect.objectContaining({ code: "INVALID_OBSERVATION" })));
  it("exposes only bounded GET and HEAD reads", async () => { const client = createReadOnlyGitHubClient(async () => fixturePage([])); await expect(client.read({ method: "GET", repositoryId: DAB2B2_REPOSITORY_ID, stream: "issues", cursor: null, etag: null })).resolves.toBeDefined(); await expect(client.read({ method: "POST" as never, repositoryId: DAB2B2_REPOSITORY_ID, stream: "issues", cursor: null, etag: null })).rejects.toMatchObject({ code: "INVALID_READ_REQUEST" }); });
  it("reconciles attributable approval without mutating canonical DAB state", async () => { const { result } = await run(); expect(result.status).toBe("succeeded"); expect(result.diagnostics.map((item) => item.code)).toEqual(["matched"]); });
  it("replays idempotently", async () => { const store = new InMemoryGitHubReconciliationRepository(); const client = new FixtureGitHubClient([fixturePage([approvalFixture()])]); const input = { repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client, store, clock, identityPolicy: policy, approvalExpectation: expectation }; const first = await reconcileGitHub(input); const second = await reconcileGitHub(input); expect(second).toEqual(first); expect(store.listEvidence()).toHaveLength(1); expect(store.listRuns()).toHaveLength(1); });
  it("handles ETag 304 without duplicate evidence", async () => { const store = new InMemoryGitHubReconciliationRepository(); await reconcileGitHub({ repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client: new FixtureGitHubClient([fixturePage([approvalFixture()])]), store, clock, identityPolicy: policy, approvalExpectation: expectation }); const result = await reconcileGitHub({ repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client: new FixtureGitHubClient([fixturePage([], { status: 304, nextCursor: null })]), store, clock, identityPolicy: policy, approvalExpectation: expectation }); expect(result.status).toBe("not_modified"); expect(store.listEvidence()).toHaveLength(1); });
  it("diagnoses stale refs", async () => { const { result } = await run([refFixture({ headSha: "0".repeat(40) })]); expect(result.diagnostics.map((item) => item.code)).toContain("stale_sha"); });
  it("diagnoses force-pushed refs", async () => { const { result } = await run([refFixture({ headSha: "1".repeat(40), previousHeadSha: "2".repeat(40) })]); expect(result.diagnostics.map((item) => item.code)).toContain("force_push_detected"); });
  it("calculates deterministic bounded primary backoff", () => expect(calculateBackoff({ observation: { kind: "primary", retryAfterSeconds: 30, resetAt: null }, attempt: 1, clock })).toEqual({ diagnostic: "rate_limited", retryAt: "2026-07-13T22:00:30.000Z", delayMs: 30000 }));
  it("honors reset time and secondary classification", () => expect(calculateBackoff({ observation: { kind: "secondary", retryAfterSeconds: null, resetAt: "2026-07-13T22:01:00.000Z" }, attempt: 0, clock }).diagnostic).toBe("secondary_rate_limited"));
  it("reports reconciliation lag without fabricating approval", () => expect(diagnoseReconciliationLag("2026-07-13T20:00:00.000Z", clock)?.code).toBe("lagging"));
  it("persists bounded rate-limit state without cursor advancement", async () => { const store = new InMemoryGitHubReconciliationRepository(); const page: GitHubReadPage = fixturePage([], { status: 429, rateLimit: { kind: "secondary", retryAfterSeconds: 10, resetAt: null } }); const result = await reconcileGitHub({ repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client: new FixtureGitHubClient([page]), store, clock, identityPolicy: policy }); expect(result.status).toBe("rate_limited"); expect(result.nextCursor.cursor).toBeNull(); expect(result.diagnostics[0].code).toBe("secondary_rate_limited"); });
  it("fails closed when the source is unavailable", async () => { const store = new InMemoryGitHubReconciliationRepository(); const result = await reconcileGitHub({ repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", client: new FixtureGitHubClient([fixturePage([], { status: 503 })]), store, clock, identityPolicy: policy }); expect(result.status).toBe("unavailable"); expect(result.diagnostics[0].code).toBe("unavailable"); });
});
