import { describe,expect,it } from "vitest";
import { pushCommittedArtifact,createBoundPullRequest,type DabGitPushReceipt,type DabGitPrReceipt,type ReceiptStore } from "../lib/dab-git-push-pr-handler.js";
import type { DabGitCommitReceipt } from "../lib/dab-git-commit-handler.js";
const commit:DabGitCommitReceipt={outcome:"verified",requestFingerprint:"a".repeat(64),idempotencyKey:"commit:key",repositoryId:"1293944511",branchName:"feature/test",parentSha:"b".repeat(40),commitSha:"c".repeat(40),treeSha:"d".repeat(40),committingAuthorizationRef:"auth:commit",actorId:"human",workloadIdentity:"apollos",files:[],committedAt:"2026-08-08T00:00:00.000Z"};
function store<T>(){const m=new Map<string,T>();return {value:{getByIdempotencyKey:async k=>m.get(k)??null,save:async(v:any)=>{m.set(v.idempotencyKey,v)}} as ReceiptStore<T>,m}}
const adapter={observeRemoteBranch:async()=>({headSha:null as string|null}),pushCommit:async(i:any)=>({branchName:i.branchName,headSha:i.commitSha}),observeBase:async()=>({baseSha:"e".repeat(40)}),createPullRequest:async(i:any)=>({prNumber:77,headBranch:i.headBranch,headSha:i.headSha,baseBranch:i.baseBranch,baseSha:i.baseSha})};
describe("DAB push + PR milestones",()=>{
 it("pushes exact commit idempotently and forbids default branch",async()=>{const s=store<DabGitPushReceipt>();const args={commitReceipt:commit,expectedRemoteSha:null,defaultBranch:"main",pushAuthorizationRef:"auth:push",authorizationUsable:true,killSwitch:false,adapterEnabled:true,handlerRegistered:true,actorId:"human",workloadIdentity:"apollos",adapter,receipts:s.value};const a=await pushCommittedArtifact(args);const b=await pushCommittedArtifact(args);expect(b).toEqual(a);expect(a.commitSha).toBe(commit.commitSha);await expect(pushCommittedArtifact({...args,commitReceipt:{...commit,branchName:"main"}})).rejects.toThrow("DAB_GIT_PUSH_DEFAULT_BRANCH_FORBIDDEN")});
 it.each([[false,false,true,true,"DAB_GIT_PUSH_AUTHORIZATION_UNUSABLE"],[true,true,true,true,"DAB_GIT_PUSH_KILL_SWITCH"],[true,false,false,true,"DAB_GIT_PUSH_ADAPTER_DISABLED"],[true,false,true,false,"DAB_GIT_PUSH_HANDLER_MISSING"]] as const)("fails push gates",async(auth,kill,en,reg,code)=>{await expect(pushCommittedArtifact({commitReceipt:commit,expectedRemoteSha:null,defaultBranch:"main",pushAuthorizationRef:"auth:push",authorizationUsable:auth,killSwitch:kill,adapterEnabled:en,handlerRegistered:reg,actorId:"h",workloadIdentity:"w",adapter,receipts:store<DabGitPushReceipt>().value})).rejects.toThrow(code)});
 it("creates exact PR idempotently with independent authorization",async()=>{const ps=store<DabGitPushReceipt>();const push=await pushCommittedArtifact({commitReceipt:commit,expectedRemoteSha:null,defaultBranch:"main",pushAuthorizationRef:"auth:push",authorizationUsable:true,killSwitch:false,adapterEnabled:true,handlerRegistered:true,actorId:"h",workloadIdentity:"w",adapter,receipts:ps.value});const rs=store<DabGitPrReceipt>();const args={pushReceipt:push,baseBranch:"main",expectedBaseSha:"e".repeat(40),prAuthorizationRef:"auth:pr",authorizationUsable:true,killSwitch:false,adapterEnabled:true,handlerRegistered:true,actorId:"h",workloadIdentity:"w",adapter,receipts:rs.value};const a=await createBoundPullRequest(args);expect((await createBoundPullRequest(args))).toEqual(a);expect(a.prNumber).toBe(77);await expect(createBoundPullRequest({...args,authorizationUsable:false,receipts:store<DabGitPrReceipt>().value})).rejects.toThrow("DAB_GIT_PR_AUTHORIZATION_UNUSABLE")});
 it("fails on base drift",async()=>{const push:DabGitPushReceipt={outcome:"verified",repositoryId:commit.repositoryId,branchName:commit.branchName,commitSha:commit.commitSha,pushAuthorizationRef:"a",actorId:"h",workloadIdentity:"w",requestFingerprint:"f",idempotencyKey:"k",pushedAt:"x"};await expect(createBoundPullRequest({pushReceipt:push,baseBranch:"main",expectedBaseSha:"f".repeat(40),prAuthorizationRef:"auth:pr",authorizationUsable:true,killSwitch:false,adapterEnabled:true,handlerRegistered:true,actorId:"h",workloadIdentity:"w",adapter,receipts:store<DabGitPrReceipt>().value})).rejects.toThrow("DAB_GIT_PR_BASE_SHA_MISMATCH")});
});
