import {describe,expect,it} from "vitest";
import {reconcileDabPullRequestCi,evaluateDabSameScopeRepair} from "../lib/dab-ci-reconciliation.js";
import type {DabGitPrReceipt} from "../lib/dab-git-push-pr-handler.js";
const pr:DabGitPrReceipt={outcome:"verified",repositoryId:"1293944511",prNumber:9,headBranch:"feature/x",headSha:"a".repeat(40),baseBranch:"main",baseSha:"b".repeat(40),prAuthorizationRef:"auth",actorId:"h",workloadIdentity:"w",requestFingerprint:"f",idempotencyKey:"k",createdAt:"x"};
const names=["Lead Intelligence CI","Coolify stack validation"];
const green=[{name:names[0],status:"completed" as const,conclusion:"success" as const},{name:names[1],status:"completed" as const,conclusion:"success" as const}];
describe("DAB CI reconciliation",()=>{
 it("accepts only exact-head/base trusted green evidence",()=>{expect(reconcileDabPullRequestCi({prReceipt:pr,observed:{prNumber:9,headSha:pr.headSha,baseSha:pr.baseSha,checks:green},trustedCheckNames:names}).outcome).toBe("green");expect(()=>reconcileDabPullRequestCi({prReceipt:pr,observed:{prNumber:9,headSha:"c".repeat(40),baseSha:pr.baseSha,checks:green},trustedCheckNames:names})).toThrow("DAB_CI_HEAD_SHA_STALE")});
 it("blocks missing, pending, and failed trusted checks",()=>{const r=reconcileDabPullRequestCi({prReceipt:pr,observed:{prNumber:9,headSha:pr.headSha,baseSha:pr.baseSha,checks:[{name:names[0],status:"completed",conclusion:"failure"}]},trustedCheckNames:names});expect(r.outcome).toBe("blocked");expect(r.blockerCodes).toContain(`trusted_check_failed:${names[0]}`);expect(r.blockerCodes).toContain(`trusted_check_missing:${names[1]}`)});
 it("permits repair only inside current approved scope and retry limit",()=>{const ci=reconcileDabPullRequestCi({prReceipt:pr,observed:{prNumber:9,headSha:pr.headSha,baseSha:pr.baseSha,checks:[{name:names[0],status:"completed",conclusion:"failure"},{name:names[1],status:"completed",conclusion:"success"}]},trustedCheckNames:names});const base={ci,currentHeadSha:pr.headSha,currentBaseSha:pr.baseSha,specHash:"s",currentSpecHash:"s",approvedPaths:["a.ts"],proposedPaths:["a.ts"],attempt:0,maxAttempts:2,repairAuthorizationUsable:true,killSwitch:false};expect(evaluateDabSameScopeRepair(base)).toEqual({allowed:true,reasonCode:"DAB_CI_REPAIR_SAME_SCOPE_ALLOWED"});expect(evaluateDabSameScopeRepair({...base,proposedPaths:["other.ts"]}).reasonCode).toBe("DAB_CI_REPAIR_SCOPE_EXPANSION");expect(evaluateDabSameScopeRepair({...base,attempt:2}).reasonCode).toBe("DAB_CI_REPAIR_ATTEMPT_LIMIT");expect(evaluateDabSameScopeRepair({...base,currentSpecHash:"new"}).reasonCode).toBe("DAB_CI_REPAIR_SPEC_STALE")});
});
