import {describe,expect,it} from "vitest";
import {verifyDabPostMerge,projectDabEngineeringMission} from "../lib/dab-post-merge-verification.js";
import type {DabGitMergeReceipt} from "../lib/dab-git-merge-handler.js";
const merge:DabGitMergeReceipt={outcome:"verified",repositoryId:"1293944511",prNumber:12,headSha:"a".repeat(40),baseSha:"b".repeat(40),mergeSha:"c".repeat(40),mergeMethod:"squash",mergeAuthorizationRef:"auth",actorId:"h",workloadIdentity:"w",requestFingerprint:"f",idempotencyKey:"k",mergedAt:"x",ciEvidenceDigest:"d".repeat(64)};
const files=[{path:"a.ts",sha256:"e".repeat(64)}];
describe("DAB post merge verification",()=>{
 it("verifies exact reachable merged tree",()=>{const r=verifyDabPostMerge({mergeReceipt:merge,defaultBranch:"main",observedDefaultHeadSha:merge.mergeSha,mergeReachable:true,approvedFiles:files,observedFiles:files});expect(r.outcome).toBe("verified");expect(projectDabEngineeringMission({taskId:"t",issueUrl:"i",prUrl:"p",heartbeatAt:"h",currentLease:null,blocker:null,awaitingApproval:false,postMerge:r,lastMilestone:"merge",nextEligibleAction:"verify"}).status).toBe("complete")});
 it("fails closed on reachability, head, or tree mismatch",()=>{expect(()=>verifyDabPostMerge({mergeReceipt:merge,defaultBranch:"main",observedDefaultHeadSha:merge.mergeSha,mergeReachable:false,approvedFiles:files,observedFiles:files})).toThrow("DAB_POST_MERGE_NOT_REACHABLE");expect(()=>verifyDabPostMerge({mergeReceipt:merge,defaultBranch:"main",observedDefaultHeadSha:"f".repeat(40),mergeReachable:true,approvedFiles:files,observedFiles:files})).toThrow("DAB_POST_MERGE_HEAD_MISMATCH");expect(()=>verifyDabPostMerge({mergeReceipt:merge,defaultBranch:"main",observedDefaultHeadSha:merge.mergeSha,mergeReachable:true,approvedFiles:files,observedFiles:[{path:"x.ts",sha256:"e".repeat(64)}]})).toThrow("DAB_POST_MERGE_TREE_MISMATCH")});
 it("projects truthful non-complete states without percentages",()=>{expect(projectDabEngineeringMission({taskId:"t",issueUrl:"i",prUrl:null,heartbeatAt:null,currentLease:"lease",blocker:null,awaitingApproval:false,postMerge:null,lastMilestone:"commit",nextEligibleAction:"push"})).toMatchObject({status:"active",humanNeeded:false,nextEligibleAction:"push"});expect(projectDabEngineeringMission({taskId:"t",issueUrl:"i",prUrl:null,heartbeatAt:null,currentLease:null,blocker:"credential_required",awaitingApproval:false,postMerge:null,lastMilestone:"commit",nextEligibleAction:null})).toMatchObject({status:"blocked",humanNeeded:true,blocker:"credential_required"})});
});
