import {createHash} from "node:crypto";
import type {DabGitMergeReceipt} from "./dab-git-merge-handler.js";
export type DabPostMergeReceipt=Readonly<{outcome:"verified";repositoryId:string;prNumber:number;mergeSha:string;defaultBranch:string;observedHeadSha:string;approvedTreeDigest:string;observedTreeDigest:string;verifiedAt:string;evidenceDigest:string}>;
export function verifyDabPostMerge(input:{mergeReceipt:DabGitMergeReceipt;defaultBranch:string;observedDefaultHeadSha:string;mergeReachable:boolean;approvedFiles:readonly {path:string;sha256:string}[];observedFiles:readonly {path:string;sha256:string}[];now?:()=>Date}):DabPostMergeReceipt{
 if(!input.mergeReachable)throw new Error("DAB_POST_MERGE_NOT_REACHABLE");if(input.observedDefaultHeadSha!==input.mergeReceipt.mergeSha)throw new Error("DAB_POST_MERGE_HEAD_MISMATCH");
 const normalize=(items:readonly {path:string;sha256:string}[])=>[...items].sort((a,b)=>a.path.localeCompare(b.path));const approved=normalize(input.approvedFiles),observed=normalize(input.observedFiles);if(JSON.stringify(approved)!==JSON.stringify(observed))throw new Error("DAB_POST_MERGE_TREE_MISMATCH");
 const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");const approvedTreeDigest=digest(approved),observedTreeDigest=digest(observed),verifiedAt=(input.now??(()=>new Date()))().toISOString();const evidenceDigest=digest({mergeSha:input.mergeReceipt.mergeSha,defaultBranch:input.defaultBranch,observedDefaultHeadSha:input.observedDefaultHeadSha,approvedTreeDigest,observedTreeDigest});return Object.freeze({outcome:"verified" as const,repositoryId:input.mergeReceipt.repositoryId,prNumber:input.mergeReceipt.prNumber,mergeSha:input.mergeReceipt.mergeSha,defaultBranch:input.defaultBranch,observedHeadSha:input.observedDefaultHeadSha,approvedTreeDigest,observedTreeDigest,verifiedAt,evidenceDigest});
}
export function projectDabEngineeringMission(input:{taskId:string;issueUrl:string;prUrl:string|null;heartbeatAt:string|null;currentLease:string|null;blocker:string|null;awaitingApproval:boolean;postMerge:DabPostMergeReceipt|null;lastMilestone:string;nextEligibleAction:string|null}){
 const status=input.postMerge?"complete":input.blocker?"blocked":input.awaitingApproval?"awaiting_approval":input.currentLease?"active":"queued";
 return Object.freeze({taskId:input.taskId,status,lastVerifiedMilestone:input.postMerge?"post_merge_verified":input.lastMilestone,nextEligibleAction:input.postMerge?null:input.nextEligibleAction,blocker:input.postMerge?null:input.blocker,humanNeeded:!input.postMerge&&(input.awaitingApproval||Boolean(input.blocker)),heartbeatAt:input.heartbeatAt,currentLease:input.currentLease,issueUrl:input.issueUrl,prUrl:input.prUrl,verificationEvidenceDigest:input.postMerge?.evidenceDigest??null});
}
