import { Router, type IRouter } from "express";
import healthRouter from "./health";
import keywordsRouter from "./keywords";
import articlesRouter from "./articles";
import articleAssetsRouter from "./article-assets";
import aiRouter from "./ai";
import contentPackagesRouter from "./content-packages";
import socialConnectionsRouter from "./social-connections";
import oauthCallbacksRouter from "./oauth-callbacks";
import leadsRouter from "./leads";
import socialPostsRouter from "./social-posts";
import autoContentRouter from "./auto-content";
import diagnosticsRouter from "./diagnostics";
import storageRouter from "./storage";
import imageAssetsRouter from "./image-assets";
import backupsRouter from "./backups";
import assessmentsRouter from "./assessments";
import gorilladeskRouter from "./gorilladesk";
import gorilladeskImportRouter from "./gorilladesk-import";
import telnyxAnalyticsRouter from "./telnyx-analytics";
import insightsRouter from "./insights";
import reviewsRouter from "./reviews";
import callIntelligenceRouter from "./call-intelligence";
import clientOnboardingRouter from "./client-onboarding";
import aiVisibilityRouter from "./ai-visibility";
import revenueAttributionRouter from "./revenue-attribution";
import aiReceptionistRouter from "./ai-receptionist";
import localPresenceRouter from "./local-presence";
import adminAssetsRouter from "./admin-assets";
import apollosRouter from "./apollos";
import discoveryRunRouter from "./discovery-run";
import discoveryInspectRouter from "./discovery-inspect";
import agentTasksRouter from "./agent-tasks";
import gbpAuditRouter from "./gbp-audit";
import gbpAiRouter from "./gbp-ai";
import competitorIntelligenceRouter from "./competitor-intelligence";
import contactRouter from "./contact";
import referralsRouter from "./referrals";
import backlinksRouter from "./backlinks";
import dabStatusRouter from "./dab-status";
import dabApprovalsRouter from "./dab-approvals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dabStatusRouter);
router.use(dabApprovalsRouter);
router.use(keywordsRouter);
router.use(articlesRouter);
router.use(articleAssetsRouter);
router.use(aiRouter);
router.use(contentPackagesRouter);
router.use(socialConnectionsRouter);
router.use(oauthCallbacksRouter);
router.use(leadsRouter);
router.use(socialPostsRouter);
router.use(autoContentRouter);
router.use(diagnosticsRouter);
router.use(storageRouter);
router.use(imageAssetsRouter);
router.use(backupsRouter);
router.use(assessmentsRouter);
router.use(gorilladeskRouter);
router.use(gorilladeskImportRouter);
router.use(telnyxAnalyticsRouter);
router.use(insightsRouter);
router.use(reviewsRouter);
router.use(callIntelligenceRouter);
router.use(clientOnboardingRouter);
router.use(aiVisibilityRouter);
router.use(revenueAttributionRouter);
router.use(aiReceptionistRouter);
router.use(localPresenceRouter);
router.use(adminAssetsRouter);
router.use(apollosRouter);
router.use(discoveryRunRouter);
router.use(discoveryInspectRouter);
router.use(agentTasksRouter);
router.use(gbpAuditRouter);
router.use(gbpAiRouter);
router.use(competitorIntelligenceRouter);
router.use(contactRouter);
router.use(referralsRouter);
router.use(backlinksRouter);

export default router;
