import { Router, type IRouter } from "express";
import healthRouter from "./health";
import keywordsRouter from "./keywords";
import articlesRouter from "./articles";
import articleAssetsRouter from "./article-assets";
import aiRouter from "./ai";
import contentPackagesRouter from "./content-packages";
import socialConnectionsRouter from "./social-connections";
import oauthCallbacksRouter from "./oauth-callbacks";
import leadsRouter from "./leads";
import leadConversionRouter from "./lead-conversion";
import socialPostRetrySafetyRouter from "./social-post-retry-safety";
import publishingIsolatedLaneRetryRouter from "./publishing-isolated-lane-retry";
import socialPostsRouter from "./social-posts";
import publishingUnresolvedDiagnosticsRouter from "./publishing-unresolved-diagnostics";
import autoContentRouter from "./auto-content";
import diagnosticsRetrySafetyRouter from "./diagnostics-retry-safety";
import diagnosticsRouter from "./diagnostics";
import storageRouter from "./storage";
import imageAssetsRouter from "./image-assets";
import backupsRouter from "./backups";
import assessmentsRouter from "./assessments";
import gorilladeskRouter from "./gorilladesk";
import gorilladeskImportRouter from "./gorilladesk-import";
import telnyxAnalyticsRouter from "./telnyx-analytics";
import insightsRouter from "./insights";
import reviewsRouter from "./reviews";
import callIntelligenceRouter from "./call-intelligence";
import clientOnboardingRouter from "./client-onboarding";
import aiVisibilityRouter from "./ai-visibility";
import revenueAttributionRouter from "./revenue-attribution";
import aiReceptionistRouter from "./ai-receptionist";
import localPresenceRouter from "./local-presence";
import adminAssetsRouter from "./admin-assets";
import apollosWeeklyPreviewRouter from "./apollos-weekly-preview";
import apollosWeeklyDeliveryStatusRouter from "./apollos-weekly-delivery-status";
import apollosPublishingStatusRouter from "./apollos-publishing-status";
import apollosRouter from "./apollos";
import discoveryRunRouter from "./discovery-run";
import discoveryInspectRouter from "./discovery-inspect";
import agentTasksRouter from "./agent-tasks";
import gbpAuditRouter from "./gbp-audit";
import gbpAiRouter from "./gbp-ai";
import competitorIntelligenceRouter from "./competitor-intelligence";
import authorityProfileRouter from "./authority-profile";
import contactRouter from "./contact";
import referralsRouter from "./referrals";
import backlinkScheduledSafetyRouter from "./backlink-scheduled-safety";
import backlinkOpportunityIntelligenceRouter from "./backlink-opportunity-intelligence";
import backlinkWorkflowActionsRouter from "./backlink-workflow-actions";
import backlinksRouter from "./backlinks";
import dabStatusRouter from "./dab-status";
import dabApprovalsRouter from "./dab-approvals";
import dabPreparationsRouter from "./dab-preparations";
import dabFirstPublishRouter from "./dab-first-publish";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dabStatusRouter);
router.use(dabApprovalsRouter);
router.use(dabPreparationsRouter);
router.use(dabFirstPublishRouter);
router.use(keywordsRouter);
router.use(articlesRouter);
router.use(articleAssetsRouter);
router.use(aiRouter);
router.use(contentPackagesRouter);
router.use(socialConnectionsRouter);
router.use(oauthCallbacksRouter);
router.use(leadsRouter);
router.use(leadConversionRouter);
router.use(socialPostRetrySafetyRouter);
router.use(publishingIsolatedLaneRetryRouter);
router.use(socialPostsRouter);
router.use(publishingUnresolvedDiagnosticsRouter);
router.use(autoContentRouter);
router.use(diagnosticsRetrySafetyRouter);
router.use(diagnosticsRouter);
router.use(storageRouter);
router.use(imageAssetsRouter);
router.use(backupsRouter);
router.use(assessmentsRouter);
router.use(gorilladeskRouter);
router.use(gorilladeskImportRouter);
router.use(telnyxAnalyticsRouter);
router.use(insightsRouter);
router.use(reviewsRouter);
router.use(callIntelligenceRouter);
router.use(clientOnboardingRouter);
router.use(aiVisibilityRouter);
router.use(revenueAttributionRouter);
router.use(aiReceptionistRouter);
router.use(localPresenceRouter);
router.use(adminAssetsRouter);
router.use(apollosWeeklyPreviewRouter);
router.use(apollosWeeklyDeliveryStatusRouter);
router.use(apollosPublishingStatusRouter);
router.use(apollosRouter);
router.use(discoveryRunRouter);
router.use(discoveryInspectRouter);
router.use(agentTasksRouter);
router.use(gbpAuditRouter);
router.use(gbpAiRouter);
router.use(competitorIntelligenceRouter);
router.use(authorityProfileRouter);
router.use(contactRouter);
router.use(referralsRouter);
router.use(backlinkScheduledSafetyRouter);
router.use(backlinkOpportunityIntelligenceRouter);
router.use(backlinkWorkflowActionsRouter);
router.use(backlinksRouter);

export default router;
