/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepurposeRouteImport } from './routes/repurpose'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepurposeIdRouteImport } from './routes/repurpose.$id'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedConnectionsStatusRouteImport } from './routes/_authenticated.connections.status'
import { Route as ApiOauthYoutubeCallbackRouteImport } from './routes/api/oauth/youtube/callback'
import { Route as ApiOauthTiktokCallbackRouteImport } from './routes/api/oauth/tiktok/callback'
import { Route as ApiOauthMetaCallbackRouteImport } from './routes/api/oauth/meta/callback'
import { Route as ApiOauthGooglePreflightRouteImport } from './routes/api/oauth/google/preflight'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth/google/callback'

const RepurposeRoute = RepurposeRouteImport.update({
  id: '/repurpose',
  path: '/repurpose',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepurposeIdRoute = RepurposeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RepurposeRoute,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsStatusRoute =
  AuthenticatedConnectionsStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedConnectionsRoute,
  } as any)
const ApiOauthYoutubeCallbackRoute = ApiOauthYoutubeCallbackRouteImport.update({
  id: '/api/oauth/youtube/callback',
  path: '/api/oauth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthTiktokCallbackRoute = ApiOauthTiktokCallbackRouteImport.update({
  id: '/api/oauth/tiktok/callback',
  path: '/api/oauth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthMetaCallbackRoute = ApiOauthMetaCallbackRouteImport.update({
  id: '/api/oauth/meta/callback',
  path: '/api/oauth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGooglePreflightRoute = ApiOauthGooglePreflightRouteImport.update({
  id: '/api/oauth/google/preflight',
  path: '/api/oauth/google/preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/publishing': typeof PublishingRoute
  '/repurpose': typeof RepurposeRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/distribution': typeof AuthenticatedDistributionRoute
  '/article/$id': typeof ArticleIdRoute
  '/repurpose/$id': typeof RepurposeIdRoute
  '/connections/status': typeof AuthenticatedConnectionsStatusRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/preflight': typeof ApiOauthGooglePreflightRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/youtube/callback': typeof ApiOauthYoutubeCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/publishing': typeof PublishingRoute
  '/repurpose': typeof RepurposeRouteWithChildren
  '/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/distribution': typeof AuthenticatedDistributionRoute
  '/article/$id': typeof ArticleIdRoute
  '/repurpose/$id': typeof RepurposeIdRoute
  '/connections/status': typeof AuthenticatedConnectionsStatusRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/preflight': typeof ApiOauthGooglePreflightRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/youtube/callback': typeof ApiOauthYoutubeCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/publishing': typeof PublishingRoute
  '/repurpose': typeof RepurposeRouteWithChildren
  '/_authenticated/connections': typeof AuthenticatedConnectionsRouteWithChildren
  '/_authenticated/distribution': typeof AuthenticatedDistributionRoute
  '/article/$id': typeof ArticleIdRoute
  '/repurpose/$id': typeof RepurposeIdRoute
  '/_authenticated/connections/status': typeof AuthenticatedConnectionsStatusRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/oauth/google/preflight': typeof ApiOauthGooglePreflightRoute
  '/api/oauth/meta/callback': typeof ApiOauthMetaCallbackRoute
  '/api/oauth/tiktok/callback': typeof ApiOauthTiktokCallbackRoute
  '/api/oauth/youtube/callback': typeof ApiOauthYoutubeCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/publishing'
    | '/repurpose'
    | '/connections'
    | '/distribution'
    | '/article/$id'
    | '/repurpose/$id'
    | '/connections/status'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/preflight'
    | '/api/oauth/meta/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/youtube/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/publishing'
    | '/repurpose'
    | '/connections'
    | '/distribution'
    | '/article/$id'
    | '/repurpose/$id'
    | '/connections/status'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/preflight'
    | '/api/oauth/meta/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/youtube/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/publishing'
    | '/repurpose'
    | '/_authenticated/connections'
    | '/_authenticated/distribution'
    | '/article/$id'
    | '/repurpose/$id'
    | '/_authenticated/connections/status'
    | '/api/oauth/google/callback'
    | '/api/oauth/google/preflight'
    | '/api/oauth/meta/callback'
    | '/api/oauth/tiktok/callback'
    | '/api/oauth/youtube/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PublishingRoute: typeof PublishingRoute
  RepurposeRoute: typeof RepurposeRouteWithChildren
  ArticleIdRoute: typeof ArticleIdRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiOauthGooglePreflightRoute: typeof ApiOauthGooglePreflightRoute
  ApiOauthMetaCallbackRoute: typeof ApiOauthMetaCallbackRoute
  ApiOauthTiktokCallbackRoute: typeof ApiOauthTiktokCallbackRoute
  ApiOauthYoutubeCallbackRoute: typeof ApiOauthYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repurpose': {
      id: '/repurpose'
      path: '/repurpose'
      fullPath: '/repurpose'
      preLoaderRoute: typeof RepurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repurpose/$id': {
      id: '/repurpose/$id'
      path: '/$id'
      fullPath: '/repurpose/$id'
      preLoaderRoute: typeof RepurposeIdRouteImport
      parentRoute: typeof RepurposeRoute
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/status': {
      id: '/_authenticated/connections/status'
      path: '/status'
      fullPath: '/connections/status'
      preLoaderRoute: typeof AuthenticatedConnectionsStatusRouteImport
      parentRoute: typeof AuthenticatedConnectionsRoute
    }
    '/api/oauth/youtube/callback': {
      id: '/api/oauth/youtube/callback'
      path: '/api/oauth/youtube/callback'
      fullPath: '/api/oauth/youtube/callback'
      preLoaderRoute: typeof ApiOauthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/tiktok/callback': {
      id: '/api/oauth/tiktok/callback'
      path: '/api/oauth/tiktok/callback'
      fullPath: '/api/oauth/tiktok/callback'
      preLoaderRoute: typeof ApiOauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/meta/callback': {
      id: '/api/oauth/meta/callback'
      path: '/api/oauth/meta/callback'
      fullPath: '/api/oauth/meta/callback'
      preLoaderRoute: typeof ApiOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/preflight': {
      id: '/api/oauth/google/preflight'
      path: '/api/oauth/google/preflight'
      fullPath: '/api/oauth/google/preflight'
      preLoaderRoute: typeof ApiOauthGooglePreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConnectionsRouteChildren {
  AuthenticatedConnectionsStatusRoute: typeof AuthenticatedConnectionsStatusRoute
}

const AuthenticatedConnectionsRouteChildren: AuthenticatedConnectionsRouteChildren =
  {
    AuthenticatedConnectionsStatusRoute: AuthenticatedConnectionsStatusRoute,
  }

const AuthenticatedConnectionsRouteWithChildren =
  AuthenticatedConnectionsRoute._addFileChildren(
    AuthenticatedConnectionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRouteWithChildren
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRouteWithChildren,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RepurposeRouteChildren {
  RepurposeIdRoute: typeof RepurposeIdRoute
}

const RepurposeRouteChildren: RepurposeRouteChildren = {
  RepurposeIdRoute: RepurposeIdRoute,
}

const RepurposeRouteWithChildren = RepurposeRoute._addFileChildren(
  RepurposeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PublishingRoute: PublishingRoute,
  RepurposeRoute: RepurposeRouteWithChildren,
  ArticleIdRoute: ArticleIdRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiOauthGooglePreflightRoute: ApiOauthGooglePreflightRoute,
  ApiOauthMetaCallbackRoute: ApiOauthMetaCallbackRoute,
  ApiOauthTiktokCallbackRoute: ApiOauthTiktokCallbackRoute,
  ApiOauthYoutubeCallbackRoute: ApiOauthYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
