import { readFileSync } from "node:fs";
import path from "node:path";
import { getTableColumns, getTableName } from "drizzle-orm";
import { describe, expect, it } from "vitest";
import { DAB2B2_REPOSITORY_ID, approvalFixture, normalizeGitHubObservation, type GitHubReconciliationSummary } from "@workspace/development-control-github";
import { InMemoryGitHubReconciliationRepository } from "../github-reconciliation-repository";
import * as schema from "../schema";

const TABLES = [schema.developmentGitHubIdentitiesTable, schema.developmentGitHubEvidenceTable, schema.developmentGitHubReconciliationCursorsTable, schema.developmentGitHubReconciliationRunsTable] as const;
const evidence = normalizeGitHubObservation(approvalFixture());
function summary(): GitHubReconciliationSummary { return Object.freeze({ runId: `github_run_${"1".repeat(64)}`, repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", status: "succeeded", evidenceIds: [evidence.evidenceId], diagnostics: [], nextCursor: { repositoryId: DAB2B2_REPOSITORY_ID, stream: "issue-18", cursor: "cursor-1", etag: "etag-1", lastObservedAt: evidence.updatedAt, retryAt: null, version: 1 } }); }

describe("DAB-2B2 durable GitHub reconciliation boundary", () => {
  it("declares exactly four additive tenant-independent tables", () => { expect(TABLES.map(getTableName)).toEqual(["development_github_identities", "development_github_evidence", "development_github_reconciliation_cursors", "development_github_reconciliation_runs"]); for (const table of TABLES) expect(Object.keys(getTableColumns(table))).not.toEqual(expect.arrayContaining(["clientId", "tenantId", "customerId", "databaseUrl"])); });
  it("keeps SQL and Drizzle tables and columns aligned", () => { const sql = readFileSync(path.join(process.cwd(), "lib/development-control-store/migrations/0002_dab2b2_github_reconciliation.sql"), "utf8"); const creates = [...sql.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map((match) => match[1]); expect(creates).toEqual(TABLES.map(getTableName)); for (const table of TABLES) { const name = getTableName(table); const block = sql.match(new RegExp(`CREATE TABLE IF NOT EXISTS ${name} \\(([\\s\\S]*?)\\n\\);`))?.[1] ?? ""; for (const column of Object.values(getTableColumns(table))) expect(block).toMatch(new RegExp(`(?:^|\\n)\\s*${column.name}\\s`, "m")); } });
  it("uses one additive non-destructive migration", () => { const sql = readFileSync(path.join(process.cwd(), "lib/development-control-store/migrations/0002_dab2b2_github_reconciliation.sql"), "utf8"); expect(sql).not.toMatch(/\b(?:DROP|TRUNCATE|ALTER TABLE|CREATE TRIGGER)\b/i); expect(sql).not.toMatch(/\b(?:client_id|tenant_id|customer_id|database_url|outbox|webhook|command_queue)\b/i); });
  it("persists evidence, run, and cursor atomically", async () => { const store = new InMemoryGitHubReconciliationRepository(); const result = await store.persistAtomic({ operationKey: "repo:stream:one", requestFingerprint: `github_request_${"2".repeat(64)}`, evidence: [evidence], summary: summary() }); expect(result).toEqual(summary()); expect(store.listEvidence()).toHaveLength(1); expect(await store.loadCursor(DAB2B2_REPOSITORY_ID, "issue-18")).toEqual(summary().nextCursor); });
  it("rolls back all fixture state on failure", async () => { const store = new InMemoryGitHubReconciliationRepository(); store.failBeforeCommit = true; await expect(store.persistAtomic({ operationKey: "repo:stream:one", requestFingerprint: `github_request_${"2".repeat(64)}`, evidence: [evidence], summary: summary() })).rejects.toMatchObject({ code: "STORE_UNAVAILABLE" }); expect(store.listEvidence()).toHaveLength(0); expect(await store.loadCursor(DAB2B2_REPOSITORY_ID, "issue-18")).toBeNull(); });
  it("replays the same request without duplicates", async () => { const store = new InMemoryGitHubReconciliationRepository(); const input = { operationKey: "repo:stream:one", requestFingerprint: `github_request_${"2".repeat(64)}`, evidence: [evidence], summary: summary() }; expect(await store.persistAtomic(input)).toEqual(await store.persistAtomic(input)); expect(store.listRuns()).toHaveLength(1); });
  it("fails closed on idempotency conflict", async () => { const store = new InMemoryGitHubReconciliationRepository(); await store.persistAtomic({ operationKey: "repo:stream:one", requestFingerprint: `github_request_${"2".repeat(64)}`, evidence: [evidence], summary: summary() }); await expect(store.persistAtomic({ operationKey: "repo:stream:one", requestFingerprint: `github_request_${"3".repeat(64)}`, evidence: [evidence], summary: summary() })).rejects.toMatchObject({ code: "IDEMPOTENCY_CONFLICT" }); });
  it("schema stores bounded normalized evidence rather than source content", () => { const columns = Object.keys(getTableColumns(schema.developmentGitHubEvidenceTable)); expect(columns).not.toEqual(expect.arrayContaining(["body", "content", "payload", "headers", "token", "rawError", "metadata"])); expect(columns).toEqual(expect.arrayContaining(["contentHash", "approvalBinding", "fingerprint"])); });
});
